version: 0.2

phases:
  install:
    commands:
      - echo Entered install phase...

  pre_build:
    commands:
      - echo Entered pre_build phase...
      # Set image tag to the first 8 characters of the commit hash string
      - IMAGE_TAG="$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | head -c 8)"
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${REGISTRY_URI}

  build:
    commands:
      - echo Entered build phase...
      # - docker build --tag ${IMAGE_NAME}:${TAG} .
      # - docker tag ${IMAGE_NAME}:${TAG} ${REGISTRY_URI}:${TAG}
      - docker build --tag ${REGISTRY_URI}:${IMAGE_TAG} .

  post_build:
    commands:
      - echo Entered post_build phase...
      - docker push ${REGISTRY_URI}:${IMAGE_TAG}
      - printf '[{"name":"hello-world", "imageUri":"%s"}]' ${REGISTRY_URI}:${IMAGE_TAG} > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files: 
    - imagedefinitions.json 
